<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3fadce96-c523-4671-bebb-1cbd8158a635</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Audit.EntityFramework.Core" />
    <PackageReference Include="Azure.Identity" VersionOverride="1.21.0" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Migrations\" />
    <Folder Include="Seeds\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ng.Pass.Server.Core\Ng.Pass.Server.Core.csproj" />
  </ItemGroup>

</Project>
