<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" VersionOverride="1.21.0" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" />
    <PackageReference Include="Microsoft.AspNetCore.Routing.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ng.Pass.Server.Core\Ng.Pass.Server.Core.csproj" />
    <ProjectReference Include="..\Ng.Pass.Server.DataLayer\Ng.Pass.Server.DataLayer.csproj" />
  </ItemGroup>
</Project>
