<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" VersionOverride="1.21.0" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Clients\" />
    <Folder Include="Entities\" />
    <Folder Include="Specifications\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ng.Pass.Server.Core\Ng.Pass.Server.Core.csproj" />
    <ProjectReference Include="..\Ng.Pass.Server.Database\Ng.Pass.Server.Database.csproj" />
  </ItemGroup>

</Project>
